version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "simple-message-topic:3:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka #This needs to be localhost when targeting locally
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  producer:
    image: com.vuba/kafka-producer:0.0.1
    ports:
      - "8081:8080"
    environment:
      KAFKA_SERVER_URL: kafka:9092
      KAFKA_TOPIC: "simple-message-topic"
  consumer-group:
    image: com.vuba/kafka-consumer:0.0.1
    environment:
      KAFKA_SERVER_URL: kafka:9092
      KAFKA_TOPIC: "simple-message-topic"
      CONSUMER_GROUP: "group"
  consumer-standalone:
    image: com.vuba/kafka-consumer:0.0.1
    environment:
      KAFKA_SERVER_URL: kafka:9092
      KAFKA_TOPIC: "simple-message-topic"
      CONSUMER_GROUP: "standalone"
